import { createThemeContract } from '@vanilla-extract/css';

// Linear-inspired token contract
export const vars = createThemeContract({
  color: {
    surface0: null,
    surface1: null,
    surface2: null,
    surface3: null,
    textPrimary: null,
    textSecondary: null,
    textTertiary: null,
    textQuaternary: null,
    brand: null,
    brandAccent: null,
    brandHover: null,
    success: null,
    borderPrimary: null,
    borderSecondary: null,
    borderTertiary: null,
    borderSubtle: null,
    borderStandard: null,
  },
  font: {
    sans: null,
    mono: null,
  },
  text: {
    xs: null,
    sm: null,
    base: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
  },
  fontWeight: {
    light: null,
    regular: null,
    medium: null,
    semibold: null,
  },
  lineHeight: {
    tight: null,
    normal: null,
    relaxed: null,
  },
  letterSpacing: {
    tight: null,
    normal: null,
  },
  radius: {
    micro: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
  space: {
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    8: null,
    10: null,
    12: null,
    16: null,
    20: null,
  },
  shadow: {
    subtle: null,
    ring: null,
    elevated: null,
    focus: null,
  },
  page: {
    paddingX: null,
    maxWidth: null,
    swatchRowMax: null,
  },
});
